In [1]:
# Q1: List Manipulation - Shopping Cart

# Step 1: Create an empty list
shopping_cart = []

# Step 2: Ask the user to input three items one by one
for i in range(3):
    item = input(f"Enter item {i+1}: ")
    shopping_cart.append(item)

# Step 3: Print the final list
print("Final Shopping Cart:", shopping_cart)

# Step 4: Remove the second item (index 1)
if len(shopping_cart) >= 2:
    removed_item = shopping_cart.pop(1)
    print(f"Removed item: {removed_item}")

# Step 5: Print the updated list
print("Updated Shopping Cart:", shopping_cart)

Enter item 1: chocolate
Enter item 2: milk
Enter item 3: eggs
Final Shopping Cart: ['chocolate', 'milk', 'eggs']
Removed item: milk
Updated Shopping Cart: ['chocolate', 'eggs']

In [3]:
# Q2: Tuple Basics - Student Information

# Step 1: Create a tuple with first name, last name, and age
student = ("John", "Doe", 19)

# Step 2: Print the entire tuple
print("Student Tuple:", student)

# Step 3: Print only the student's last name using indexing
print("Last Name:", student[1])

Student Tuple: ('John', 'Doe', 19)
Last Name: Doe

In [5]:
# Q3: Dictionary - Phone Book

# Step 1: Create an empty dictionary
phone_book = {}

# Step 2: Add three key-value pairs (name: phone number)
phone_book["Alice"] = "9876543210"
phone_book["Bob"] = "9123456780"
phone_book["Charlie"] = "9988776655"

# Step 3: Print the entire dictionary
print("Phone Book:", phone_book)

# Step 4: Ask the user for a name
name = input("Enter a name to search: ")

# Step 5: Print the phone number or handle if not found
if name in phone_book:
    print(f"{name}'s phone number is: {phone_book[name]}")
else:
    print(f"Sorry, {name} not found in phone book.")

Phone Book: {'Alice': '9876543210', 'Bob': '9123456780', 'Charlie': '9988776655'}
Enter a name to search: Bob
Bob's phone number is: 9123456780

In [6]:
# Q4: List of Tuples - Movie Collection

# Step 1: Create a list of movie tuples
movies = [("Inception", 2010), ("Toy Story", 1995), ("Interstellar", 2014)]

# Step 2: Add a new movie tuple
movies.append(("The Dark Knight", 2008))

# Step 3: Loop through the list and print each movie
print("Movie Collection:")
for title, year in movies:
    print(f"- {title} (Released in {year})")

Movie Collection:
- Inception (Released in 2010)
- Toy Story (Released in 1995)
- Interstellar (Released in 2014)
- The Dark Knight (Released in 2008)

In [7]:
# Q5: Dictionary Nesting - Employee Directory

# Step 1: Create a dictionary with employee information
employee = {
    "name": "John Doe",
    "department": "IT",
    "skills": ["Python", "SQL", "Java"]
}

# Step 2: Print employee's name
print("Employee Name:", employee["name"])

# Step 3: Print employee's second skill (index 1)
if len(employee["skills"]) >= 2:
    print("Second Skill:", employee["skills"][1])
else:
    print("This employee has less than 2 skills.")

Employee Name: John Doe
Second Skill: SQL

In [8]:
# Q6: Converting Data Types

# Step 1: Create a list of names
names_list = ['Alice', 'Bob', 'Charlie']
print("Original List:", names_list)

# Step 2: Convert the list into a tuple
names_tuple = tuple(names_list)
print("Converted Tuple:", names_tuple)

# Step 3: Try to change the first element of the tuple
try:
    names_tuple[0] = 'David'
except TypeError as e:
    print("Error:", e)

Original List: ['Alice', 'Bob', 'Charlie']
Converted Tuple: ('Alice', 'Bob', 'Charlie')
Error: 'tuple' object does not support item assignment

In [9]:
# Q7: Membership Testing (Lists & Dictionaries)

# Step 1: Create a list of fruits
fruits = ['apple', 'banana', 'mango']

# Step 2: Ask the user for a fruit
fruit_name = input("Enter a fruit name: ").lower()

# Step 3: Check if the fruit is in the list
if fruit_name in fruits:
    print(f"Yes, we have {fruit_name}s!")
else:
    print(f"Sorry, {fruit_name} is not in the list.")

# Step 4: Dictionary with fruit prices
prices = {'apple': 1.0, 'banana': 0.5, 'orange': 0.75}

# Step 5: Check if the fruit is in dictionary keys
if fruit_name in prices:
    print(f"{fruit_name.capitalize()} is available in the price list at ${prices[fruit_name]}")
else:
    print(f"{fruit_name.capitalize()} is not listed in the price dictionary.")

Enter a fruit name: apple
Yes, we have apples!
Apple is available in the price list at $1.0

In [10]:
# Q8: Combining Lists and Dictionaries - Gradebook

# Step 1: Create the dictionary with student names and their scores
grades = {
    "Alice": [85, 90, 78],
    "Bob": [92, 88, 95],
    "Charlie": [70, 75, 80]
}

# Step 2: Choose a student (e.g., Alice)
student_name = "Alice"

# Step 3: Calculate the average
if student_name in grades:
    scores = grades[student_name]
    average = sum(scores) / len(scores)
    print(f"{student_name}'s average score: {average:.2f}")
else:
    print(f"Student {student_name} not found in gradebook.")

Alice's average score: 84.33

In [11]:
# Q9: Tuple Unpacking - Coordinates

# Step 1: Create a tuple representing a 2D coordinate
point = (5, -3)

# Step 2: Unpack the tuple into x and y
x, y = point

# Step 3: Print the values of x and y
print("x-coordinate:", x)
print("y-coordinate:", y)

# Step 4: Calculate distance from origin
distance = (x**2 + y**2) ** 0.5
print("Distance from origin:", distance)

x-coordinate: 5
y-coordinate: -3
Distance from origin: 5.830951894845301

In [12]:
# Q10: Comprehensive Practice - Restaurant Order

# Step 1: Create a dictionary for the menu
menu = {
    "pizza": 250,
    "burger": 150,
    "pasta": 200,
    "salad": 120,
    "coffee": 80
}

# Step 2: Create an empty order list
order = []

# Step 3: Ask the customer for two items
print("Menu:", menu)
for i in range(2):
    item = input(f"Enter item {i+1} from the menu: ").lower()
    if item in menu:
        order.append(item)
    else:
        print(f"Sorry, {item} is not available.")

# Step 4: Calculate the total cost
total = sum(menu[item] for item in order)

# Step 5: Print the total bill
print("Your order:", order)
print("Total Bill Amount:", total)

Menu: {'pizza': 250, 'burger': 150, 'pasta': 200, 'salad': 120, 'coffee': 80}
Enter item 1 from the menu: pizza
Enter item 2 from the menu: coffee
Your order: ['pizza', 'coffee']
Total Bill Amount: 330